name: Check Style
on: push

jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3

      - name: Install tools
        run: python -m pip install --upgrade pip pycodestyle

      - name: Debug - Show current directory
        run: pwd

      - name: Debug - List all files in the repository
        run: ls -R

      - name: Debug - List Python files
        run: ls -l src/*.py || echo "No Python files found"

      - name: Check Style
        run: |
          if ls src/*.py 1> /dev/null 2>&1; then
            pycodestyle --first src/*.py
          else
            echo "No Python files to check."